### ISSUE TITLE
wrong adapter file in Illumina templates

### ISSUE THREAD

**Issue by visoca** [dariogf/SeqtrimNext#4]
There is something wrong with the default Illumina template files (genomics_short_reads.txt, genomics_short_reads_2.txt, transcriptomics_short_reads.txt). Using them throw the following error:

> I, [2016-12-01 17:10:13#21763]  INFO -- : SeqTrimNext version 2.0.66
I, [2016-12-01 17:10:13#21763]  INFO -- : STN command:  /usr/local/ruby/current/bin/seqtrimnext
I, [2016-12-01 17:10:13#21763]  INFO -- : Using BLASTDB: /usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/DB/formatted
I, [2016-12-01 17:10:13#21763]  INFO -- : Using options: {"server_ip":"0.0.0.0","port":0,"workers":6,"only_workers":false,"check_db":false,"use_checkpoint":false,"install_db":null,"logfile":"#<IO:0x007fc088846200>","fastq":["./seq_1.fq.gz","./seq2.fq.gz"],"format":null,"fasta":null,"qual":null,"list_db":null,"list_db_name":"ALL","gen_params":false,"template":"./transcriptomics_short_reads.txt","chunk_size":5000,"json":null,"skip_output":false,"skip_report":false,"write_in_gzip":false}
I, [2016-12-01 17:10:13#21763]  INFO -- : Using init file: /usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/init_env
I, [2016-12-01 17:10:13#21763]  INFO -- : Using params file: transcriptomics_short_reads.txt
I, [2016-12-01 17:10:13#21763]  INFO -- : Used FastQ format for input files: sanger
I, [2016-12-01 17:10:13#21763]  INFO -- : Loading params
D, [2016-12-01 17:10:13#21763] DEBUG -- : read: plugin_list =PluginIndeterminations,PluginFindPolyAt,PluginAbAdapters,PluginUserContaminants,PluginContaminants,PluginVectors,PluginLowQuality,PluginLowComplexity
D, [2016-12-01 17:10:13#21763] DEBUG -- : read: contaminants_db="contaminants.fasta cont_ribosome.fasta"
D, [2016-12-01 17:10:13#21763] DEBUG -- : read: generate_initial_stats =false
D, [2016-12-01 17:10:13#21763] DEBUG -- : read: min_insert_size_trimmed =30
D, [2016-12-01 17:10:13#21763] DEBUG -- : read: remove_clonality=false
D, [2016-12-01 17:10:13#21763] DEBUG -- : read: adapters_ab_db="adapters_illumina.fasta"
I, [2016-12-01 17:10:13#21763]  INFO -- : Checking global params
I, [2016-12-01 17:10:13#21763]  INFO -- : Loading actions
I, [2016-12-01 17:10:14#21763]  INFO -- : Loading plugins [PluginIndeterminations,PluginFindPolyAt,PluginAbAdapters,PluginUserContaminants,PluginContaminants,PluginVectors,PluginLowQuality,PluginLowComplexity,PluginExtractInserts]
I, [2016-12-01 17:10:14#21763]  INFO -- : Check plugin params
DB file /usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/DB/formatted/adapters_illumina.fasta not formatted
E, [2016-12-01 17:10:14#21763] ERROR -- : PluginAbAdapters found following errors:
E, [2016-12-01 17:10:14#21763] ERROR -- :    -Param adapters_ab_db is not a valid DB. Current value is #"adapters_illumina.fasta"#. Can't format database. We don't have write permissions in: /usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/DB/formatted/adapters_illumina.fasta
USED DATABASES
"/usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/DB/formatted/cont_ribosome.fasta /usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/DB/formatted/contaminants.fasta"
USED DATABASES
"/usr/local/ruby/2.0.0/lib/ruby/gems/2.0.0/gems/seqtrimnext-2.0.66/lib/seqtrimnext/DB/formatted/vectors.fasta"
E, [2016-12-01 17:10:14#21763] ERROR -- : Plugin check failed

I am not sure if this fix is appropriate, but I have overcome this by including adapters_illumina DB in `lib/seqtrimnext/classes/install_database.rb`:
```
  1 require 'open-uri'
  2 
  3 class InstallDatabase
  4 
  5 
  6   def initialize(type,db_path)
  7 
  8
  9     types=['core', **'adapters_illumina',** 'cont_bacteria','cont_fungi','cont_mitochondrias','cont_plastids','cont_ribosome','cont_viruses']
```
followed by installation and formatting:
```
seqtrimnext -i adapters_illumina
seqtrimnext -c
```

**Comment by dariogf** [comment]
Thanks visoca, the solution that you have pathched yourself is the only one. I will fix STN trunk for next release.
